using PathFinder.MapGeneration;

namespace PathFinder;

public interface IPathFinder
{
    /// <summary>
    /// Method to find the path from point A to point B
    /// </summary>
    /// <param name="map">The autogenerated map</param>
    /// <param name="start">Start point of the path</param>
    /// <param name="destination">End point of the path</param>
    /// <returns>List of points represents the path and the count of visited nodes</returns>
    public (List<Point>, int) FindPath(string[,] map, Point start, Point destination);
    
    
}